[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pool_program = "7oHnDkpPbhPacDfqzF38caM3eo1Xo7cBmFugNXJurnn3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p pool-program"
