//! Generates `programs/pool-program/src/vk.rs` from
//! `circuits/build/verification_key.json` — the snarkjs-exported Groth16
//! verifying key for the membership circuit, converted to the
//! `groth16-solana` byte layout via `prover::g1_to_solana_be`/`g2_to_solana_be`
//! (the same helpers `crates/prover`'s tests use to assert the on-chain byte
//! format accepts a real proof). Keeping exactly one conversion
//! implementation means the embedded VK and any proof produced by
//! `prover::prove_membership` are guaranteed to speak the same byte format.

use ark_bn254::{Fq, Fq2, G1Affine, G1Projective, G2Affine, G2Projective};
use serde_json::Value;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn workspace_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(Path::parent)
        .expect("crates/vk-gen is two levels below the workspace root")
        .to_path_buf()
}

fn fq_from_decimal(s: &str) -> Fq {
    use std::str::FromStr;
    Fq::from(num_bigint::BigUint::from_str(s).expect("decimal field element"))
}

fn g1_from_json(el: &Value) -> G1Affine {
    let a = el.as_array().expect("G1 point is a 3-element array");
    let x = fq_from_decimal(a[0].as_str().expect("G1 x is a decimal string"));
    let y = fq_from_decimal(a[1].as_str().expect("G1 y is a decimal string"));
    let z = fq_from_decimal(a[2].as_str().expect("G1 z is a decimal string"));
    G1Affine::from(G1Projective::new(x, y, z))
}

fn g2_from_json(el: &Value) -> G2Affine {
    let a = el.as_array().expect("G2 point is a 3-element array");
    let coord = |v: &Value| -> Fq2 {
        let c = v.as_array().expect("Fq2 coordinate is a 2-element array");
        Fq2::new(
            fq_from_decimal(c[0].as_str().expect("Fq2 c0 is a decimal string")),
            fq_from_decimal(c[1].as_str().expect("Fq2 c1 is a decimal string")),
        )
    };
    G2Affine::from(G2Projective::new(coord(&a[0]), coord(&a[1]), coord(&a[2])))
}

fn fmt_byte_array(bytes: &[u8]) -> String {
    let mut out = String::from("[\n");
    for chunk in bytes.chunks(16) {
        out.push_str("        ");
        for b in chunk {
            let _ = write!(out, "{b:#04x}, ");
        }
        out.push('\n');
    }
    out.push_str("    ]");
    out
}

/// Renders `programs/pool-program/src/vk.rs` from a parsed
/// `verification_key.json`. Pure string formatting so it's trivially
/// testable without touching the filesystem.
fn render_vk_rs(v: &Value) -> String {
    assert_eq!(
        v["protocol"], "groth16",
        "expected a groth16 verification key"
    );
    assert_eq!(v["curve"], "bn128", "expected the bn128 (BN254) curve");

    let n_public = v["nPublic"].as_u64().expect("nPublic is a number") as usize;
    assert_eq!(
        n_public, 3,
        "membership circuit must expose exactly 3 public inputs (root, nullifierHash, extDataHash)"
    );

    let alpha_g1 =
        prover::g1_to_solana_be(&g1_from_json(&v["vk_alpha_1"])).expect("alpha_g1 to solana bytes");
    let beta_g2 =
        prover::g2_to_solana_be(&g2_from_json(&v["vk_beta_2"])).expect("beta_g2 to solana bytes");
    let gamma_g2 =
        prover::g2_to_solana_be(&g2_from_json(&v["vk_gamma_2"])).expect("gamma_g2 to solana bytes");
    let delta_g2 =
        prover::g2_to_solana_be(&g2_from_json(&v["vk_delta_2"])).expect("delta_g2 to solana bytes");
    let ic: Vec<[u8; 64]> = v["IC"]
        .as_array()
        .expect("IC is an array")
        .iter()
        .map(|p| prover::g1_to_solana_be(&g1_from_json(p)).expect("IC point to solana bytes"))
        .collect();
    assert_eq!(ic.len(), n_public + 1, "vk_ic must have nPublic+1 entries");

    let mut ic_src = String::from("&[\n");
    for point in &ic {
        ic_src.push_str("        ");
        ic_src.push_str(&fmt_byte_array(point));
        ic_src.push_str(",\n");
    }
    ic_src.push_str("    ]");

    format!(
        "// @generated by crates/vk-gen from circuits/build/verification_key.json — do not edit.\n\
         pub const MEMBERSHIP_VK: groth16_solana::groth16::Groth16Verifyingkey = groth16_solana::groth16::Groth16Verifyingkey {{\n\
         \x20   nr_pubinputs: {n_public},\n\
         \x20   vk_alpha_g1: {alpha_g1},\n\
         \x20   vk_beta_g2: {beta_g2},\n\
         \x20   vk_gamme_g2: {gamma_g2},\n\
         \x20   vk_delta_g2: {delta_g2},\n\
         \x20   vk_ic: {ic_src},\n\
         }};\n",
        alpha_g1 = fmt_byte_array(&alpha_g1),
        beta_g2 = fmt_byte_array(&beta_g2),
        gamma_g2 = fmt_byte_array(&gamma_g2),
        delta_g2 = fmt_byte_array(&delta_g2),
    )
}

/// Renders `vk.rs` into a temporary file and runs `rustfmt` over it so the
/// output byte-matches what `cargo fmt --check` expects of the committed
/// file, then returns the formatted contents. Used by both generate mode
/// (written to the real output path) and `--check` mode (compared in memory
/// without touching the committed file).
fn render_and_format(v: &Value) -> String {
    let rendered = render_vk_rs(v);

    let tmp_path = std::env::temp_dir().join(format!("vk-gen-{}.rs", std::process::id()));
    std::fs::write(&tmp_path, &rendered)
        .unwrap_or_else(|e| panic!("failed to write temp file {}: {e}", tmp_path.display()));

    let status = std::process::Command::new("rustfmt")
        .arg(&tmp_path)
        .status()
        .unwrap_or_else(|e| panic!("failed to run rustfmt on {}: {e}", tmp_path.display()));
    if !status.success() {
        let _ = std::fs::remove_file(&tmp_path);
        panic!("rustfmt failed on {}", tmp_path.display());
    }

    let formatted = std::fs::read_to_string(&tmp_path)
        .unwrap_or_else(|e| panic!("failed to read back {}: {e}", tmp_path.display()));
    let _ = std::fs::remove_file(&tmp_path);
    formatted
}

fn load_vk_json(root: &Path) -> Value {
    let vk_json_path = root.join("circuits/build/verification_key.json");
    let raw = std::fs::read_to_string(&vk_json_path).unwrap_or_else(|e| {
        panic!(
            "failed to read {} ({e}) — run `bash circuits/scripts/setup.sh` first",
            vk_json_path.display()
        )
    });
    serde_json::from_str(&raw).expect("valid JSON")
}

fn main() {
    let check_mode = std::env::args().any(|a| a == "--check");
    let root = workspace_root();
    let v = load_vk_json(&root);
    let out_path = root.join("programs/pool-program/src/vk.rs");

    if check_mode {
        let expected = render_and_format(&v);
        let committed = std::fs::read_to_string(&out_path).unwrap_or_else(|e| {
            panic!(
                "failed to read committed {} ({e}) — nothing to check against",
                out_path.display()
            )
        });
        if expected == committed {
            println!(
                "check-vk: {} matches circuits/build/verification_key.json",
                out_path.display()
            );
            return;
        }
        eprintln!(
            "check-vk: DRIFT DETECTED — {} does not match what would be regenerated from \
             circuits/build/verification_key.json. Run `cargo run -p vk-gen` and commit the \
             result.",
            out_path.display()
        );
        std::process::exit(1);
    }

    let rendered = render_and_format(&v);
    std::fs::write(&out_path, rendered).unwrap_or_else(|e| {
        panic!("failed to write {}: {e}", out_path.display());
    });

    println!("wrote {}", out_path.display());
}

#[cfg(test)]
mod tests {
    use super::*;
    use ark_ec::AffineRepr;

    fn g1_json(p: G1Affine) -> Value {
        serde_json::json!([
            p.x().expect("affine point is not at infinity").to_string(),
            p.y().expect("affine point is not at infinity").to_string(),
            "1"
        ])
    }

    fn g2_json(p: G2Affine) -> Value {
        let x = p.x().expect("affine point is not at infinity");
        let y = p.y().expect("affine point is not at infinity");
        serde_json::json!([
            [x.c0.to_string(), x.c1.to_string()],
            [y.c0.to_string(), y.c1.to_string()],
            ["1", "0"]
        ])
    }

    #[test]
    fn renders_expected_shape_for_a_minimal_vk() {
        let g1 = G1Affine::generator();
        let g2 = G2Affine::generator();
        let json = serde_json::json!({
            "protocol": "groth16",
            "curve": "bn128",
            "nPublic": 3,
            "vk_alpha_1": g1_json(g1),
            "vk_beta_2": g2_json(g2),
            "vk_gamma_2": g2_json(g2),
            "vk_delta_2": g2_json(g2),
            "IC": [g1_json(g1), g1_json(g1), g1_json(g1), g1_json(g1)],
        });
        let rendered = render_vk_rs(&json);
        assert!(rendered.contains("pub const MEMBERSHIP_VK"));
        assert!(rendered.contains("nr_pubinputs: 3"));
        assert!(rendered.contains("vk_gamme_g2:"));
        assert!(!rendered.contains("vk_gamma_g2:"));
    }
}
